### ISSUE TITLE
Passing args to sbt-server

### ISSUE THREAD

**Issue by jan0sch** [cb372/sbt-client#7]
While I was fiddling with adjusting `vim-scala` to this really, really cool thin client for sbt I stumbled upon errors when trying to pass arguments to sbt. I used sbt 1.2.8 and sbt-client 0.1.1.

### Example

A sbt server was started manually before executing the commands below.

```
% sbt-client compile
[info] Processing
[success] Done
% sbt-client -Dsbt.log.noformat=true compile
[info] Processing
[error] sbt failed to execute our command. Error code: -33000, message: ''
[error] Error from sbt
```

The shell of the manually started sbt gives the following output:

```
[info] new client connected: network-2
[error] Expected symbol
[error] Not a valid command: -
[error] Expected end of input.
[error] Expected '--'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] -Dsbt.log.noformat=true compile
[error]  ^
```

Can this be fixed on the `sbt-client` side or is this an issue with the sbt-server?

**Comment by cb372** [comment]
See https://github.com/cb372/sbt-client/issues/1#issuecomment-452069218

The problem is that args like `-Dsbt.log.noformat=true` can only be passed when starting sbt, not at the level of a single command. And sbt-client will only start the server if it’s not already running.

Sbt-client could accept the arg and throw it away if the server is already running, but I think that behaviour would be pretty confusing. Better suggestions welcome!

**Comment by jan0sch** [comment]
Seems like this can't be fixed. I'll think of some workaround on the vim side.
